# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20696052791104ea72671e55312a5a3e506ca08f9ea604ab6904a956d2a4f5f09c161ad5c74dba228785b3d68b1a6709723b9a7e05c08cf78353b5ab05290a15

test:
  secret_key_base: ec76d1027f49f42a317f8d5fc4a1b5ed980c4c535449b69d8bc30b7b940cc263b3c196c95fb6851f8cc1ca5736abe0b91ed6f1f97fd4e0044dcabe786aec3f03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
